### ISSUE TITLE
Data listing sorts alphabetically

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/Webcharts#178] opened 2018-01-30 14:33 UTC
Sorting within the data listing yields results that are in alphabetical order, rather than numerical

![image](https://user-images.githubusercontent.com/14914918/35571568-8108609a-05a0-11e8-8034-3496c6eb54d5.png)

**Comment by samussiah** [comment] 2018-10-09 14:09
potential duplicate of #123

**Comment by jwildfire** [comment] 2019-11-18 17:27
Closing as duplicate

**Closed by jwildfire** 2019-11-18 17:27 UTC
Labels: duplicate
